import tailwindcss_opentype from "tailwindcss-opentype";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'display': ['Consta'],
        'body': ['Consta'],
        'v2Card': ['EB Garamond'],
        'dsGlyphs': ['DS Open Glyphs'],
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        'action-card': '#367F36',
        'action-card-20': '#d0dac8',
        'action-card-30': '#bdceb7',
        'action-card-40': '#abc3a7',
        'action-card-50': '#98b797',
        'maneuver-card': '#365B7F',
        'maneuver-card-20': '#d0d3d3',
        'maneuver-card-30': '#bdc3c8',
        'maneuver-card-40': '#abb5bd',
        'maneuver-card-50': '#98a6b3',
        'triggered-action-card': '#7F3636',
        'triggered-action-card-20': '#deccc5',
        'triggered-action-card-30': '#d2b9b3',
        'triggered-action-card-40': '#c6a8a2',
        'triggered-action-card-50': '#ba9591',
        'free-triggered-action-card': '#7F367F',
        'free-triggered-action-card-20': '#deccce',
        'free-triggered-action-card-30': '#d2b9c1',
        'free-triggered-action-card-40': '#c6a8b4',
        'free-triggered-action-card-50': '#ba95a7',
        'free-maneuver-card': '#367F5A',
        'free-maneuver-card-20': '#d0dad2',
        'free-maneuver-card-30': '#bdcec6',
        'free-maneuver-card-40': '#abc3ba',
        'free-maneuver-card-50': '#98b7af',
        'routine-card': '#36367F',
        'routine-card-20': '#d0cdd0',
        'routine-card-30': '#bcbac4',
        'routine-card-40': '#a9a9b7',
        'routine-card-50': '#d6ccd3',
        'passive-card': '#5A367F',
        'passive-card-20': '#d6ccd3',
        'passive-card-30': '#c6b9c8',
        'passive-card-40': '#b6a8bd',
        'passive-card-50': '#a695b3',
        'free-strike-card': '#595959',
        'free-strike-card-20': '#dedad3',
        'free-strike-card-30': '#d2cec8',
        'free-strike-card-40': '#c6c3bd',
        'free-strike-card-50': '#bab7b3',
        'treasure-card': '#333333',
        'treasure-card-20': '#EDE1BC',
        'treasure-card-30': '#E8D9A5',
        'treasure-card-40': '#E4D091',
        'treasure-card-50': '#DEC879',
        'move-action-card': '#7F5A36',
        'move-action-card-20': '#DED3C4',
        'move-action-card-30': '#D2C4B2',
        'move-action-card-40': '#C7B5A1',
        'move-action-card-50': '#B9A58E',
        'cardback': '#ffffff',
        'keyword-backing': '#b87f47',
        'bubble-gum': '#ff77e9',
        'bermuda': '#78dcca',
        'regal-blue': '#243c5a',
        'ash-yellow': '#f9c710',
        'sidebar-back': '#e5e7e6',
        'sidebar-trim': '#c0c0c0',
      },
    },
  },
  plugins: [
    tailwindcss_opentype,
    require('@tailwindcss/typography'),
  ],
}
